Added ClientServer#isTransferring
mattmalec/Pterodactyl4J pull request #36
Opened 2021-08-06 17:58 UTC by lokerhp

I added ClientServer#isTransferring in this PR, isInstalling and isSuspended already existed so I added isTransferring

2021-08-08 02:25 UTC, mattmalec requested changes
See the commit comment for details.

2021-08-08 02:25 UTC, mattmalec commented on src/main/java/com/mattmalec/pterodactyl4j/client/entities/impl/ClientServerImpl.java
> +		return json.getBoolean("is_transferring");
Can you show where this is returned in the client API? Just want to see the raw JSON for this object.

2021-08-14 19:20 UTC, lokerhp commented
I added a commit which also fixes a small Javadoc mistake I noticed.

I've also sended the raw JSON data in your Discord DM @mattmalec

2021-08-15 15:18 UTC, mattmalec approved these changes
Thanks! This will work.

2021-08-15 15:19 UTC, merged

2021-08-15 15:19 UTC, mattmalec commented
Thanks for fixing that documentation too, good catch.