Eh added a bit of docs before I make a bigger pr with way more docs
mattmalec/Pterodactyl4J pull request #53
Opened 2022-05-19 07:41 UTC by shmezi

no clue what I did but hopefully this works ?

2022-05-19 08:24 UTC, lokerhp commented on src/main/java/com/mattmalec/pterodactyl4j/DataType.java
> +	 * DataType format for Kilo-Bytes
Can’t this be just Kilobytes?

2022-05-19 12:00 UTC, shmezi commented on src/main/java/com/mattmalec/pterodactyl4j/DataType.java
> +	 * DataType format for Kilo-Bytes
Could yes, Just wanted to be clear, really just preference-based feel free to change it tho.

2022-05-19 13:48 UTC, mattmalec commented on src/main/java/com/mattmalec/pterodactyl4j/DataType.java
> +	 * DataType format for Kilo-Bytes
Since this is your PR, you would have to be the one to change it

2022-05-19 13:52 UTC, mattmalec requested changes
I'm noticing that quite a bit of code was reformatted in a way that breaks a lot of Javadoc comments that I had written out. 

I'm trying to think of there's an easier way to fix it besides manually going through all the files.

2022-05-19 14:02 UTC, shmezi commented
Do you use a plugin to format or something, if so maybe I can just add it so it fixes that

2022-05-26 22:48 UTC, mattmalec requested changes
Overall, I'm pretty impressed you actually went through all these files and was able to document it. There's a few parts that can be picked up and I realize they're kinda nitty, but these are the types of things that can make you stand out when writing docs.

2022-05-26 22:48 UTC, mattmalec commented on src/main/java/com/mattmalec/pterodactyl4j/DataType.java
> +	 * DataType format for Giga-Bytes
For stuff like this, you don't need to document each individual enum. They're pretty self-explanatory as it is.

2022-05-26 22:48 UTC, mattmalec commented on src/main/java/com/mattmalec/pterodactyl4j/UtilizationState.java
> +     * Represents when the server is online
In this scenario, this makes sense to document the enum. I like what you did here :)

2022-05-26 22:48 UTC, mattmalec commented on src/main/java/com/mattmalec/pterodactyl4j/client/entities/ClientServer.java
> + * Represents a {@link PteroClient}'s server
I would check how I did this with the [ApplicationServer](https://github.com/mattmalec/Pterodactyl4J/blob/develop/src/main/java/com/mattmalec/pterodactyl4j/application/entities/ApplicationServer.java#L27-L37) implementation. I'd ideally like to keep everything using the same conventions if possible.

2022-05-26 22:48 UTC, mattmalec commented on src/main/java/com/mattmalec/pterodactyl4j/client/entities/ClientSubuser.java
> + * Represents a sub-user pm a {@link ClientServer}
Spelling mistake here. Also, like mentioned earlier, I would check how it's documented with [User](https://github.com/mattmalec/Pterodactyl4J/blob/develop/src/main/java/com/mattmalec/pterodactyl4j/entities/User.java#L19-L22)

2022-05-26 22:48 UTC, mattmalec commented on src/main/java/com/mattmalec/pterodactyl4j/client/entities/ClientSubuser.java
> +     * Gets the uuid of the {@link ClientSubuser}
The description and return value are kinda recursive here and explain the same thing. It's important to notate if this method can return null at all.
```suggestion
	 * The UUID of the Server.
	 *
	 * @return Never-null {@link java.util.UUID} containing the Subuser's UUID.
	 */
	UUID getUUID();
```

2022-05-26 22:48 UTC, mattmalec commented on src/main/java/com/mattmalec/pterodactyl4j/client/entities/PteroClient.java
> + * Represents the access to a user's server panel
You should see how it's documented in [PteroApplication](https://github.com/mattmalec/Pterodactyl4J/blob/develop/src/main/java/com/mattmalec/pterodactyl4j/application/entities/PteroApplication.java#L29-L33)

2022-05-26 22:48 UTC, mattmalec commented on src/main/java/com/mattmalec/pterodactyl4j/client/entities/PteroClient.java
> +     * @throws com.mattmalec.pterodactyl4j.exceptions.LoginException If the API key is incorrect
None of these throws docs should be moved at all - they were formatted specifically like that. There's a bunch more instances where they've been moved, but this comment should suffice for them.

2022-05-26 22:48 UTC, mattmalec commented on src/main/java/com/mattmalec/pterodactyl4j/client/entities/Utilization.java
> + 	 * @return weather the server is suspended
Spelling mistake here. You should look around the project to see how we document boolean return values.
Example: [ApplicationEgg](https://github.com/mattmalec/Pterodactyl4J/blob/develop/src/main/java/com/mattmalec/pterodactyl4j/application/entities/ApplicationEgg.java#L111-L116)

2022-05-26 22:48 UTC, mattmalec commented on src/main/java/com/mattmalec/pterodactyl4j/client/entities/SFTP.java
> + * Represents Pterodactyl {@link SFTP} connection info
I would be more clearer with what this actually is, including the method docs. Check out how we document [Database](https://github.com/mattmalec/Pterodactyl4J/blob/develop/src/main/java/com/mattmalec/pterodactyl4j/entities/Database.java#L73-L88)

2022-05-26 22:48 UTC, mattmalec commented on src/main/java/com/mattmalec/pterodactyl4j/client/entities/Utilization.java
> +	 * @return the formatted string representation of the currently used disk space
We don't normally want to start lines with a lowercase letter. The example kind of looks out of place - maybe we can clean that up so it's bit clearer.

2022-05-26 22:48 UTC, mattmalec commented on src/main/java/com/mattmalec/pterodactyl4j/client/entities/Utilization.java
> +	 * Get the current disk space usage
This stuff is very recursive. We also don't want to start our doc with "Get" if weren't not actually running any logic to actually "get" the value, we're just returning data that's already there.
```suggestion
	 * The raw amount of disk space currently being used by this Server.
	 * @return The raw amount of disk space, usually in {@link DataType#MB} form
```

2022-05-26 22:48 UTC, mattmalec commented on src/main/java/com/mattmalec/pterodactyl4j/client/entities/Utilization.java
> +	 * Get the current ram usage
Stuff like this, same thing as my previous comment on disk space.

2022-05-26 22:48 UTC, mattmalec commented on src/main/java/com/mattmalec/pterodactyl4j/client/entities/ClientServer.java
> + * Represents a {@link PteroClient}'s server
I'm also kinda confused why this is all spaced out now.

2022-05-26 22:48 UTC, mattmalec commented on src/main/java/com/mattmalec/pterodactyl4j/application/entities/Nest.java
> + * Represents a Pterodactyl {@link Nest}
This can be explained better too. I should have some comments around the review saying the same thing.

2022-05-26 22:48 UTC, mattmalec commented on src/main/java/com/mattmalec/pterodactyl4j/application/entities/ApplicationUser.java
> + * Represents a user on a {@link ApplicationServer} server
This can be explained better too. Also still confused on why these lines are spread out.

2022-05-26 22:48 UTC, mattmalec commented on src/main/java/com/mattmalec/pterodactyl4j/UtilizationState.java
> + * Represents a server's state.
Thanks :)

2022-05-27 14:08 UTC, shmezi commented
Ok nice, sorry for any mistakes.. first pr I've made on open source stuff..

2022-05-27 14:35 UTC, mattmalec commented
No need to apologize! It's hard to get a PR right the first time on an open source project. My biggest nit is consistency - making sure the docs are consistent and helpful across the entire project. I meant it when I said I was impressed, a couple of things to clean up, but you really did a great job :)

2026-01-10 16:56 UTC, closed without merging