Feature: Node: setMaintanceMode
mattmalec/Pterodactyl4J pull request #74
Opened 2023-12-27 17:10 UTC by DerMistkaefer

This PR introduces the functionality to set a Node into Maintenance Mode.

API Doc:
https://dashflo.net/docs/api/pterodactyl/v1/
<img width="549" alt="image" src="https://github.com/mattmalec/Pterodactyl4J/assets/15692249/a0e9bcd8-b725-409b-ac8a-8ed33cda93f9">

2023-12-28 09:07 UTC, lokerhp commented
Personally I would change hasMaintanceMode into isInMaintenanceMode or inMaintenanceMode or something like that

2024-01-01 16:11 UTC, DerMistkaefer commented
Thank you for your suggestion regarding the naming convention.
Based on your feedback, I have updated the property to a more descriptive name, `isInMaintenanceMode`.
However, I have decided to keep the function name as `setMaintanceMode` to maintain consistency with the existing getter `hasMaintanceMode`, as referenced in [Entity Node L45](https://github.com/mattmalec/Pterodactyl4J/blob/develop/src/main/java/com/mattmalec/pterodactyl4j/application/entities/Node.java#L45). 
This balance allows us to improve clarity while preserving coherence in our codebase.

2024-01-02 04:47 UTC, mattmalec requested changes
hey there! thanks so much for your contribution to p4j! just some small nitty changes, and then it should be good to go :)

2024-01-02 04:47 UTC, mattmalec commented on src/main/java/com/mattmalec/pterodactyl4j/requests/action/AbstractNodeAction.java
> +	public NodeAction setMaintanceMode(boolean isInMaintenanceMode) {
we should deprecate this method and make a new method that spells maintenance correctly. the old method can just call the new one

2024-01-02 04:47 UTC, mattmalec commented on src/main/java/com/mattmalec/pterodactyl4j/application/managers/NodeAction.java
> +	NodeAction setMaintanceMode(boolean isInMaintenanceMode);
think of writing getters as if you're asking a question. in our case, asking if the node is in maintenance mode is correctly defined as `isInMaintenanceMode`. however, for setters, this logic generally doesn't apply - the variable name should be prescriptive instead.

i think naming this `maintenanceMode` is more than okay. we should only use `isInMaintenanceMode` for the getter, but internally pass `maintenanceMode` around

2024-01-02 04:47 UTC, mattmalec commented on src/main/java/com/mattmalec/pterodactyl4j/requests/action/AbstractNodeAction.java
> +	public NodeAction setMaintanceMode(boolean isInMaintenanceMode) {
also see above comments on variable naming

2024-01-02 17:16 UTC, DerMistkaefer commented
Thank you for your feedback. I don't want to change to old function but when you say it is okay then let's go.
Now we use correct naming.

2024-01-13 12:31 UTC, DerMistkaefer commented
@mattmalec can we please merge this?

2024-01-13 15:15 UTC, mattmalec requested changes
super quick changes and i will approve + merge today

2024-01-13 15:15 UTC, mattmalec commented on src/main/java/com/mattmalec/pterodactyl4j/application/entities/Node.java
> +	 * @deprecated Use {@link #isInMaintenanceMode()} instead
docstrings should be formatted [like this](https://github.com/mattmalec/Pterodactyl4J/blob/develop/src/main/java/com/mattmalec/pterodactyl4j/client/entities/PteroClient.java#L38-L49)

2024-01-13 15:15 UTC, mattmalec commented on src/main/java/com/mattmalec/pterodactyl4j/application/entities/Node.java
> +	 * @deprecated Use {@link #isInMaintenanceMode()} instead
also make sure to clarify that it's only deprecated to fix the spelling error

2024-01-14 09:46 UTC, DerMistkaefer commented on src/main/java/com/mattmalec/pterodactyl4j/application/entities/Node.java
> +	 * @deprecated Use {@link #isInMaintenanceMode()} instead
Okay I fixed the ranking in den docstring and add a notice about the reason of the deprecation.

2024-04-07 16:28 UTC, mattmalec approved these changes
looks good!

2024-06-23 13:20 UTC, merged