RateLimiter removes request from queue on failure
mattmalec/Pterodactyl4J pull request #77
Opened 2024-01-12 14:53 UTC by Raft08

Added finally block to the try catch of the RateLimiter#run() and moved the iterator.remove() call to the finally block

2024-04-07 15:36 UTC, Raft08 commented
Any updates on this pr?

2024-04-07 16:34 UTC, mattmalec commented
i think the thing to do here would be to validate the url inside of the endpoint config rather than removing the request from the ratelimiter ([here should work](https://github.com/mattmalec/Pterodactyl4J/blob/develop/src/main/java/com/mattmalec/pterodactyl4j/utils/config/EndpointConfig.java#L28)). the reason this doesn't look like it works as expected is because it's never reaching the part where retry backoff is supposed to occur

2024-04-09 16:52 UTC, Raft08 commented
@mattmalec Here are the changes you requested, I reverted my last changes and added URL validation using a Regex

2024-04-09 17:17 UTC, mattmalec requested changes

2024-04-09 17:17 UTC, mattmalec commented on src/main/java/com/mattmalec/pterodactyl4j/utils/Checks.java
> +	public static void validateUrl(String url, String name) {
i would preferably avoid regex when possible. perhaps this could work?

```suggestion
	public static void validateUrl(String url, String name) {
	notNull(url, name);
	try {
            new URL(url);
        } catch (MalformedURLException e) {
            throw new IllegalArgumentException(name + " must be a valid URL!");
        }
}
```

2024-04-09 18:16 UTC, Raft08 commented on src/main/java/com/mattmalec/pterodactyl4j/utils/Checks.java
> +	public static void validateUrl(String url, String name) {
I was originally planned to do like this, but I though you would prefer to use a Regex, to me it's all good!

2024-05-28 05:53 UTC, closed without merging